version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::859254246490:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-q7ZPjyPM3AWh"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::859254246490:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-66Qhro8CLiFD"
cloudformation_execution_role = "arn:aws:iam::859254246490:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-UHQl2gvPYwIb"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1vlmqa7ah8neo"
image_repository = ""
region = "us-east-2"
